"""empty message

Revision ID: 456e7a492f6b
Revises: 151301173c4b
Create Date: 2018-07-29 12:32:46.099413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456e7a492f6b'
down_revision = '151301173c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_task_id')
    # ### end Alembic commands ###
