"""empty message

Revision ID: 5da9d9a0935d
Revises: eb9c11380cd8
Create Date: 2018-07-26 21:58:16.141081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da9d9a0935d'
down_revision = 'eb9c11380cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('deadline', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'deadline')
    # ### end Alembic commands ###
