"""empty message

Revision ID: 6968fcffd4bb
Revises: 456e7a492f6b
Create Date: 2018-07-29 12:48:43.252419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6968fcffd4bb'
down_revision = '456e7a492f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('stashed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'stashed')
    # ### end Alembic commands ###
