"""empty message

Revision ID: 7cbb7bf04a2c
Revises: 23a7d357614d
Create Date: 2018-07-26 19:31:41.318186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbb7bf04a2c'
down_revision = '23a7d357614d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'complete')
    # ### end Alembic commands ###
