"""tests table

Revision ID: 7f0c00f44495
Revises: ea4aea020799
Create Date: 2018-12-26 16:46:56.051114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0c00f44495'
down_revision = 'ea4aea020799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testname', sa.String(length=140), nullable=True),
    sa.Column('score', sa.String(length=140), nullable=True),
    sa.Column('accuracy', sa.String(length=140), nullable=True),
    sa.Column('reaction_time', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_timestamp'), 'test', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_timestamp'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
