"""empty message

Revision ID: 8a5849539a2b
Revises: 6968fcffd4bb
Create Date: 2018-08-03 01:52:06.173649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5849539a2b'
down_revision = '6968fcffd4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('location', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'location')
    # ### end Alembic commands ###
