"""empty message

Revision ID: eb9c11380cd8
Revises: 7cbb7bf04a2c
Create Date: 2018-07-26 21:50:05.255336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9c11380cd8'
down_revision = '7cbb7bf04a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'last_updated')
    # ### end Alembic commands ###
